[build]
command = "pip install -r requirements.txt && python3 build.py"
publish = "dist"
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.9"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/health"
to = "/.netlify/functions/health"
status = 200

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"